[versions]
guava = "33.4.6-jre"
junit-jupiter = "5.12.1"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit_jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
