/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.7.0"
}

rootProject.name = "code-society-25-2"

include("lib:java:codedifferently-instructional:instructional-lib")
include("lesson_02:quiz_app")
