/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import com.codedifferently.instructional.quiz.AnswerChoice;
import com.codedifferently.instructional.quiz.MultipleChoiceQuizQuestion;
import com.codedifferently.instructional.quiz.QuizConfig;
import com.codedifferently.instructional.quiz.QuizQuestion;
@SpringBootTest
class LessonTest {

    @Autowired
    private QuizConfig quizConfig;

    @Autowired
    private List<MultipleChoiceQuizQuestion> quizQuestions;
    

    private static final int EXPECTED_NUMBER_OF_QUESTIONS = 11;

    private void getQuestions() {
        this.quizQuestions = Lesson.makeQuestions();
    }

    @BeforeEach
    public void setUp() {
        Path quizPath = Paths.get("src", "main", "resources", "quiz.yaml"); 
        quizConfig = new QuizConfig();
        

        getQuestions();
    }

    

    @Test
    public void checkQuizQuestions_areAssembledCorrectly() {
        // Expect the right number of questions
        assertEquals(EXPECTED_NUMBER_OF_QUESTIONS, quizQuestions.size());

        // Expect questions to be numbered correctly
        for (int i = 0; i < quizQuestions.size(); i++) {
            assertEquals(i, quizQuestions.get(i).getQuestionNumber());
        }
    }

    @Test
    public void checkQuizQuestions_promptsAreUnique() {
        Set<String> questionPrompts = new HashSet<>();
        for (QuizQuestion q : quizQuestions) {
            questionPrompts.add(q.getQuestionPrompt());
        }
        assertEquals(EXPECTED_NUMBER_OF_QUESTIONS, questionPrompts.size());
    }

    @Test
    public void checkQuestions_answeredCorrectly() throws Exception {

        assertEquals(quizQuestions.size(), quizConfig.size("default"));

        for (QuizQuestion question : quizQuestions) {
            String actualAnswer = question.getAnswer();

            // Check that the question was answered
            assertNotEquals(AnswerChoice.UNANSWERED, actualAnswer);

            // Check that the answer is correct
            assertTrue(
                quizConfig.checkAnswer(
                    "default",
                    question.getQuestionNumber(),
                    actualAnswer
                )
            );
        }
    }
    
}
