/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LessonTest {
    @Test void lessonHasQuestions() {
        assertNotNull(Lesson.makeQuestions(), "lesson should have questions");
        assertTrue(Lesson.makeQuestions().length > 0, "lesson should have at least one question");
    }
}
