/*
 * This source file was generated by the Gradle 'init' task
 */
package com.tyranricejr.primejava;

/*
 * Title: IsAPrimeNumber.java
 * 
 * Description: This class contains a method to check if a number is prime.
 * 
 * Created by: Tyran Rice Jr.
 * Date: 2023-10-01
 */
public class PrimeChecker {

    /*
     * Title: isPrime
     * 
     * Description: This method checks if a given number is prime.
     * 
     * Parameters:
     * - number: an integer to check for primality.
     * 
     * Returns:
     * - true if the number is prime, false otherwise.
     */
    public static boolean isPrime(int number) {
        if (number <= 1) {
            return false;
        }
        for (int i = 2; i <= Math.sqrt(number); i++) {
            if (number % i == 0) {
                return false;
            }
        }
        return true;
    }
}
