name: Check Lesson 02 Pull Request

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "lesson_02/quiz_java/**"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build Lesson 02 with Java
      working-directory: ./lesson_02/quiz_java
      run: ./gradlew check