name: Check Push

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/check_push.yml"
      - "lib/**"
      - "lesson_02/quiz/**"
      - "lesson_03/quiz/**"
      - "lesson_06/quiz/**"
      - "lesson_06/expression/**"
      - "lesson_07/conditionals/**"
      - "lesson_09/types/**"
      - "lesson_10/libraries/**"
      - "lesson_11/arrays_java/**"
      - "lesson_11/arrays_ts/**"
      - "lesson_12/structs_java/**"
      - "lesson_12/structs_ts/**"
      - "lesson_13/maps_java/**"
      - "lesson_13/maps_ts/**"
      - "lesson_14/exceptions/**"
      - "lesson_15/tdd/**"
      - "lesson_16/objects/**"
      - "lesson_17/bank/**"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: "8.11.1"

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Build Shared Lib with Gradle Wrapper
      working-directory: ./lib/java/codedifferently-instructional
      run: ./gradlew check

    - name: Build Shared Lib with Node.js
      working-directory: ./lib/javascript/codedifferently-instructional
      run: |
        npm ci
        npm run test

    - name: Build Fullstack Demo with Java
      working-directory: ./lib/java/fullstack_demo
      env:
        CLERK_PERISHABLE_KEY: 12345
        CLERK_SECRET_KEY: 12345
      run: ./gradlew check

